#+TITLE: emacs - labs127.io and me
#+AUTHOR: Kholid Fuadi
#+DATE: <2015-10-01 Thu>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../stylesheet.css" />
#+STARTUP: indent


* Menjalankan emacs secara daemon
Emacs terasa lambat saat /startup/? Bahkan dengan processor *i7 4790
RAM 8GB*, dengan jumlah /packages/ yang tidak terlalu banyak juga,
kadang =emacs= terasa lambat ketika /startup/.

Untuk menghindari hal ini, saya coba menggunakan fitur =daemon= yang
tersedia /by default/ di =emacs=. Caranya adalah sebagai berikut:

Jalankan perintah ini di =console=:

#+BEGIN_SRC sh
emacs --daemon
#+END_SRC

Sekarang =emacs= sudah berjalan secara /daemon/ di /background/. Untuk
menjalankan /client/ =emacs=, jalankan perintah berikut:

#+BEGIN_SRC sh
# jalankan emacs window mode
emacsclient -c -n /path/to/your/dir/or/file
# jalankan emacs no-window mode
emacsclient /path/to/your/dir/or/file
#+END_SRC

Perubahannya? Sangat signifikan! bahkan terasa lebih cepat membuka
=emacs= dibanding membuka aplikasi =terminal=.

Jika pingin lebih efektif lagi, Anda bisa menambahkan =emacs --daemon=
setiap kali mesin Anda boot.

Lagi, saya membuat /custom/ =alias= di =.bashrc= sebagai berikut:

#+BEGIN_SRC text
# alias emacs client
alias emacs='emacsclient -n -c'

# autostrat emacs --daemon if it's not running yet
export ALTERNATE_EDITOR=""
#+END_SRC

/Reload/ konfigurasi =bash= Anda:

#+BEGIN_SRC sh
source ~/.bashrc
#+END_SRC

Sumber[fn:1]

* Mode Fullscreen di Emacs
Salah satu cara untuk mengurangi /distraction/ ketika sedang /coding/
adalah dengan membuat layar /editor/ menjadi /fullscreen/. Kalau
bekerja di =terminal=, kita dapat dengan mudah menekan =F11= untuk
mengaktifkan mode /fullscreen/. Bagaimana dengan =emacs=? Bisa tapi
butuh sedikit /tweak/ di =.emacs=.

Tambahkan baris kode berikut di =.emacs= Anda:

#+BEGIN_SRC lisp
;; F11 key to toggle full screen mode
(defun toggle-fullscreen ()
  (interactive)
  (set-frame-parameter nil 'fullscreen 
		       (if (frame-parameter nil 'fullscreen)
			   nil
			 'fullboth)))

(global-set-key [f11] 'toggle-fullscreen)
#+END_SRC

/Reload/ konfigurasi dengan =M-x load-file= =~/.emacs=. Sekarang coba
tekan =F11=, dan layar =emacs= akan berubah menjadi /fullscreen/!
Tekan =F11= sekali lagi untuk kembali ke ukuran /window/ sebelumnya.
* Customize Saved
Ingin menghilangkan toolbar, menubar, scrollbar?  Sebagai contoh, saya
ingin menghilangkan scroll bar di sebelah kanan, ketikkan fungsi
berikut:

=M-x customize-saved=

Kemudian search /scroll bar/ tekan /Return/ kemudian ubah nilai, dan tekan
Apply and Save.
* Emacs Good Reads
- [[http://home.fnal.gov/~neilsen/notebook/orgExamples/org-examples.html][Emacs org-mode examples and cookbook]]

* Footnotes

[fn:1] http://emacs-fu.blogspot.co.id/2009/02/emacs-daemon.html
